### ISSUE TITLE
Problem in uploading pictures from local directory

### ISSUE THREAD

**Issue by maniacinsane** [Kami/python-face-client#2]
When a picture is given as an URL, the wrapper seems to work perfectly, however the same picture stored in the local drive when called for face_detect (for example) throws up the following error :

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\python27\lib\site-packages\face_client\face_client.py", line 77, in f
aces_detect
    response = self.send_request('faces/detect', data)
  File "c:\python27\lib\site-packages\face_client\face_client.py", line 328, in
send_request
    raise FaceError(response_data['error_code'], response_data['error_message'])

face_client.face_client.FaceError: INVALID_ARGUMENTS_VALUE - Can only upload ima
ge files (406)

**Comment by Kami** [comment]
I have tried to replicate your problem today, but I couldn't do it.

Are you sure that the file you trying to upload is a valid image? Maybe the image is corrupted?
