### ISSUE TITLE
not getting mood features

### ISSUE THREAD

**Issue by nitinbravi** [Kami/python-face-client#3]
Hello, 
I have a bunch of face images for which I am trying to find the features. I noticed that the output response when implemented through the python code does not give me any mood feature, while the same image when uploaded through the API sandbox online recognizes the mood feature. I do not find any  discrepancy for other features such as gender, smile etc & this problem exists for all the images in my database. 
I find this to be extremely peculiar and I could not figure the reason. The mood feature is something that would be useful to me and the python wrapper serves my purpose. 
I greatly appreciate any help or clarification. 
Thanks in advance.
Nitin

**Comment by Kami** [comment]
Fixed in d90d5b4ef58d67375a82766c1396161245e3a70a.

Thanks for reporting it. I will publish an updated version to PyPi later this week.

**Comment by nitinbravi** [comment]
Great! It works. Thanks.
